version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: HotelManagementSystem
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3308:3306"
